config/routes.rb
Rails.application.routes.draw do
  resources :readings, only: %i[index create new]
  devise_for :users
  get '/search', to: 'readings#search', as: :search, defaults: { format: :turbo_stream }
  root 'readings#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/level_validator.rb
class LevelValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, _value)
    return if record.reading_count <= 4

    record.errors.add attribute, (options[:message] || 'can only be store 4 times per day')
  end
end

app/models/reading.rb
class Reading < ApplicationRecord
  belongs_to :user
  validates :level, presence: true, level: true
  validates_length_of :level, maximum: 1
  validates_numericality_of :level, only_integer: true
  attr_accessor :reading_count

  scope :today, -> { where('created_at > ?', Time.current.beginning_of_day) }
  scope :monthly, -> { where('created_at > ?', 1.month.ago) }
  scope :month_to_date, ->(data) { where('created_at > ? and created_at <= ?', Time.current.beginning_of_month, data) }
  scope :reading_count_of_day, -> { today.count }
  before_validation :set_reading_count

  def set_reading_count
    count = User.find_by(id: user_id).readings.reading_count_of_day if user_id.present?
    self.reading_count = count || 0
  end

  def full_error_message
    errors.full_messages.to_sentence.capitalize
  end
end

app/models/reading_report.rb
class ReadingReport
  def self.search(user, query)
    case query
    when 'Daily'
      user.readings.today
    when 'Monthly'
      user.readings.monthly
    else
      user.readings.month_to_date(query)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :readings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  def index
    authorize Reading

    @readings = current_user.readings.today
  end

  def create
    @reading = current_user.readings.create(reading_params)
    authorize(@reading)
    if @reading.valid?
      redirect_to root_path, notice: 'Glucose level was successfully added.'
    else
      flash[:alert] = @reading.full_error_message
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @reading = Reading.new
  end

  def search
    @readings = ReadingReport.search(current_user, params[:q]) if params[:q].present?
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace('readings',
                                                  partial: 'reading',
                                                  locals: { readings: @readings })
      end
    end
  end

  private

  def reading_params
    params.require(:reading).permit(:level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_msg_class(type)
    case type
    when 'notice'
      'bg-info'
    when 'alert'
      'bg-danger'
    else
      ''
    end
  end
end

app/helpers/readings_helper.rb
module ReadingsHelper
  def reading_header(params)
    "Report by #{params}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloodGlucoseTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |type, msg| %>
        <div class="text-white text-center mt-2 <%= flash_msg_class(type)%>">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/readings/_reading.html.erb
<%= turbo_frame_tag "readings" do %>
<h3><%= reading_header(params["q"]) %></h3>

    <% if readings.present? %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Maximum</th>
                    <th scope="col">Minimum</th>
                    <th scope="col">Average</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><%= readings.maximum(:level)%>mg/dl</td>
                    <td><%= readings.minimum(:level)%>mg/dl</td>
                    <td><%= readings.average(:level)%>mg/dl</td>
                </tr>
            </tbody>
        </table> 
     <% else %>
         No records were found
     <% end %>   
<% end %>

app/views/readings/_reading_list.html.erb
<%= turbo_frame_tag "readings" do %>
    <h3>Daily Readings</h3>
    <% if readings.present? %>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Level</th>
                </tr>
            </thead>
            <tbody>
                <% readings.each_with_index do  |reading, index| %>
                    <tr>
                        <td><%= index +1 %></td>
                        <td><%= reading.level%>mg/dl</td>
                    </tr>
                 <% end %>   
            </tbody>
        </table> 
     <% else %>
         No records were found
     <% end %>   
<% end %>

app/views/readings/index.html.erb
<button class='btn btn-primary mt-2'>
    <%= link_to 'Add Glucose Reading', new_reading_path, class: 'text-white' %>
</button>
<hr>
<div class="row">
    <div class="col-md-8">
    <%= render "reading_list", readings: @readings %>
    </div>
    <div class="col-md-4">
        <h3>Search Report By</h3>
        <p><%= link_to 'Daily', search_path(q: 'Daily') %></p>
        <p><%= link_to 'Monthly', search_path(q: 'Monthly') %></p>
        <%= form_with(url: search_path, method: :get, data: { turbo_frame: 'readings', turbo_action: 'advance' }) do |f| %>
            <%= f.date_field :q, autofocus: true, class: 'form-control w-50 ', placeholder: 'Select date' %>
            <div class="my-3">
                <%= f.submit 'Search', class: 'btn btn-primary' %>
            </div>
        <% end %>
    </div>
</div>

app/views/readings/new.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2 class="pb-4"><%= link_to 'Reading', readings_path %></h2>
        <%= form_for @reading, url: readings_path, method: :post do |f| %>
            <%= f.label :glucose_level, class: "form-label" %>
            <%= f.number_field :level, autofocus: true, class: 'form-control' %>
            <div class="my-3">
                <%= f.submit 'Create Reading', class: 'btn btn-primary' %>
            </div>
        <% end %>
    </div>
</div>